# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "rss"
name = "RSS"
url = "https://revontulet.dev/index.xml"

[social.params]
icon = "rss"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/MisterDerpie"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/matthias-doepmann/"

[social.params]
icon = "brand-linkedin"
